version: '2'
services:
  frontend:
    build:
      context: .
    command: sh -c "npm run lint && npm test && node e2e-ci.js"
    environment:
      - ELASTICSEARCH_URL=http://es:9200
      - KARMA_BROWSERS=selenium_chrome
      - KARMA_SINGLE_RUN=true
      - SELENIUM_HOST=selenium
    depends_on:
      - selenium
  backend:
    build:
      context: backend
    command: npm start
    environment:
      - ELASTICSEARCH_URL=http://es:9200
    depends_on:
      - es
  selenium:
    image: selenium/standalone-chrome:3.12.0
    depends_on:
      - backend
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
